/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AnalysisResult {
  hasComponent: boolean
  filePath: string
  dependencies: Array<string>
  transformations: Array<Transformation>
}

export declare function analyzeAndTransformCode(code: string, filePath: string): string

export declare function analyzeFile(filePath: string): AnalysisResult

export declare function analyzeFileChanged(filePath: string, event: string): void

export interface Transformation {
  start: number
  end: number
  replacement: string
}
