/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ComponentInfo {
  name: string
  found: boolean
}
export declare function transformWithAnalysis(code: string, filePath: string): string
